### PR TITLE
fix: `d.group.name` should return group name instead of group index

### PR DESCRIPTION
**Pull request by trim21**
I'm new to C++, sorry if it's not correct.

### CODE REVIEW

**Comment by rakshasa** [comment]
Post logs of when you're calling the command with and without this change.

**Comment by trim21** [comment]
I didn't use tui but header less server with xmlrpc what log do you want? The output of this command?

**Comment by rakshasa** [comment]
Yes, just the output of the xmlrpc commands.

**Comment by trim21** [comment]
first create a download and get it's info_hash, then:

```py
client.xml_call("choke_group.insert", ["", "test"])
client.xml_call("d.group.set", [info_hash.upper(), "test"])
group_name = client.xml_call("d.group.name", [info_hash.upper()])
print(type(group_name), repr(group_name))
```

before it's `<class 'int'> 1` and after it's `<class 'str'> 'test'`

**Comment by trim21** [comment]
Do we have a plan for a new release?

**Pull request merged**
