### PR TITLE
Update rtorrent.rc

### PR DESCRIPTION
**Pull request by g0tmi1k**
Useful: 
- https://media.readthedocs.org/pdf/rtorrent-docs/latest/rtorrent-docs.pdf
- https://rtorrent-docs.readthedocs.io/en/latest/ 
- https://github.com/rakshasa/rtorrent/wiki/rTorrent-0.9-Comprehensive-Command-list-(WIP)
- https://github.com/rakshasa/rtorrent/blob/master/src/command_local.cc

### CODE REVIEW

**Comment by pyroscope** [comment]
If you put the socket file into /tmp, i.e. a shared dir, then at least qualify it with the PID or the username. And a way better place is ``session.path``.

**Comment by g0tmi1k** [comment]
@pyroscope Thanks for the suggestion. Updated.

**Comment by pyroscope** [comment]
Also, if you don't use the modern wiki template, at least surgically remove the cancer that the horrible `stop_untied` schedule is. Problems caused by this are a FAQ.

**Comment by g0tmi1k** [comment]
Removed `stop_untied` as your request @pyroscope .
I had a quick look at the FAQ (https://github.com/rakshasa/rtorrent/blob/master/doc/faq.xml), and ctrl+F didn't have anything about it, nor could I see anything in the wiki (https://github.com/rakshasa/rtorrent/wiki) about it.

I've added the "sample" config in (`rtorrent.rc-sample`) from the wiki, but would it be better to replace this `rtorrent.rc` completely with it?
I personally wouldn't, but it sounds like it may be helpful?
I wouldn't as it would be "nice" to see all the possible options there are to put in a config file (are any missing still?)

Also`feature-bind` branch is ahead of master but a bit (Jan 2018), which hasn't been updated in some time (Oct 2016). The pull request best going into master? [cc: @rakshasa]

**Comment by pyroscope** [comment]
Look at reddit, there it is a FAQ, over several years.

**Comment by g0tmi1k** [comment]
https://www.reddit.com/r/rtorrent/wiki/index

```
forbidden (reddit.com)
you are not allowed to do that

— wiki_disabled.
```

**Comment by pyroscope** [comment]
For “all the possible options there are” see the common tasks page, https://rtorrent-docs.readthedocs.io/en/latest/use-cases.html, and https://rtorrent-docs.readthedocs.io/en/latest/cmd-ref.html. 

A starter config has to stick to the essentials, else you overwhelm people.

**Comment by g0tmi1k** [comment]
@pyroscope I agree a starter config should be basic as it does overwhelm/confuse people.

I also believe there should be a place to go with all the options/configs listed in a single place (which is what I though `rtorrent.rc` was). Guessing the website is more up-to-date. Is it worth linking in either/both `rtorrent.rc*` files to that place so its easier for others to find?

**Comment by chros73** [comment]
> The pull request best going into master?

That's correct, master branch.

**Comment by pyroscope** [comment]
> Is it worth linking in either/both rtorrent.rc* files to that place so its easier for others to find?
The new one is, the old stinky one won't be.

**Comment by g0tmi1k** [comment]
@pyroscope Added a ton of useful resources to the old one, pointing to the new style.
What else would be needed/recommended for the merge?

**Comment by pyroscope** [comment]
Put anything in there not on common tasks on common tasks – that is much more discoverable and useful.

**Comment by g0tmi1k** [comment]
@pyroscope Like how it is?

**Comment by g0tmi1k** [comment]
Fix merge conflicts (due to #677)

**Comment by g0tmi1k** [comment]
🎉

**Pull request merged**
