### PR TITLE
Additional layout for Download List.

### PR DESCRIPTION
**Pull request by merzlya**
In order to switch between compact and standart layout press "L" (upper case) or added "download_list_layout = 1" to ~/.rtorrent.rc
rtorrent

### CODE REVIEW

**Comment by chros73** [comment]
Are you familiar with rtorrent-ps? https://github.com/pyroscope/rtorrent-ps
Pyroscope has implemented similar things long time ago. I understand that he uses unicode characters that can be problematic with systems without proper locale support (e.g. OpenWRT).

**Comment by merzlya** [comment]
No, I'm not familiar with rtorrent-ps. I use rtorrent and I'm pretty happy with it.
This patch makes it more handy for me and maybe someone finds it useful too.

**Comment by chros73** [comment]
@merzlya: If you run debian flavored OS, the give it a try.
I just finished [my fork](https://github.com/chros73/rtorrent-ps#fork-notes) of [rtorrent-ps](https://github.com/pyroscope/rtorrent-ps) (adding more info to it). 
My mod looks like this:
rtorrent-ps-ch-0 9 6-happy-pastel-kitty-s

Don't get me wrong, your patch can be still useful with systems without proper locale support (e.g. OpenWRT). The question is how important to support this feature.

**Comment by rakshasa** [comment]
Cleaned up and merged in #474.

**Pull request closed without merging**
