### PR TITLE
travis: Fix test in wrong path, and jobs parallelization

### PR DESCRIPTION
**Pull request by MindTooth**
Cut a lot out of my previous PR.  Now it just fixes the wrong path, and moves the parallelization into an environment variable.

Closes #728.

### CODE REVIEW

**Comment by rakshasa** [comment]
It now seems to fail travis builds.

**Comment by MindTooth** [comment]
Yes, because it now tests the `rtorrent` source code, not building `libtorrent` twice.  Unless that was the goal from the start.

I thought it were pulled & build `libtorrent` only as a dependency, and the `make check` were for `rtorrent`.  Current form will never test the `rtorrent` source AFAIK.

**Comment by MindTooth** [comment]
Ended up putting in on multiple lines.  Also, maybe an idea to include newer toolchains?  Know that it won't compile on macOS, as it's been removed from Homebrew.

**Comment by MindTooth** [comment]
Ended up putting in on multiple lines. Also, maybe an idea to include newer toolchains? Know that it won't compile on macOS, as it's been removed from Homebrew.

**Comment by MindTooth** [comment]
Figured I would give this another try.  After some testing inside a clean [Ubuntu Trusty VM](https://app.vagrantup.com/ubuntu/boxes/trusty64), it compiles just fine after I've installed the dependancies.  But when I use a clean file on Travis-CI, it breaks on `make check`.  I suspect Travis-CI is at falt.  I'll be doing some more research what might cause this.

The `.travis.yml` file:
```yml
language: cpp

addons:
  apt:
    packages:
      - libcppunit-dev
    update: true

# TODO: Use the same branch name if libtorrent has it.
before_install:
 - git clone https://github.com/rakshasa/libtorrent.git
 - |
   pushd libtorrent \
   && ./autogen.sh \
   && ./configure \
   && make \
   && sudo make install \
   && popd

script:
- ./autogen.sh && ./configure && make
- if [ ! $SKIP_CHECK ]; then make check; fi
```

**Comment by MindTooth** [comment]
Woot!  I find the issue; needed to add `--prefix=/usr` to libtorrent configure.

Now it succeeds with all compilers.

**Comment by MindTooth** [comment]
Been thinking about also adding more environments to the matrix.  The current toolchains is a bit out of date.  The default Ubuntu image is now defaulting to xenial (16.04 LTS), and I would believe that the default toolchain have changed.

_(If the idea is to build libtorrent twice, I understand, and I'll close this PR.)_

**Pull request merged**
