### PR TITLE
Allow rtorrent to run as a daemon without screen.  implements issue #36

### PR DESCRIPTION
**Pull request by sallyswiss**
this checks if running in a terminal before initializing ncurses with initscr and then does not initialize if not a terminal.  this means rtorrent can run as a daemon but will still function normally under normal conditions.

### CODE REVIEW

**Comment by rakshasa** [comment]
In any case the 'have term' needs to be a variable that can be set (see src/command_*.cc) and default to true.

**Comment by wheelerlaw** [comment]
What is the status of this?

**Comment by rakshasa** [comment]
Status is that the patch defaults to daemon while that should be the non-default option set by a properly named system.daemon.enable variable (or something).

For someone who what's this merged, forged the branch, merge the latest develop, then add the (very easy to add) variable and checks to have the proper behavior.

Make a new pull request, attribute the original developers above, and make something I want to merge.

**Comment by o6uoq** [comment]
+1

**Pull request closed without merging**
